Repository OG-star-tech/OG-star-tracker-, pull requests merged in 2025-08, with the labels that each got.

#71 fix goto ra steps/s calculation
  esp32_wireless_control/firmware/axis.cpp
  esp32_wireless_control/firmware/consts.h
  esp32_wireless_control/firmware/tracking_rates.cpp
  esp32_wireless_control/firmware/tracking_rates.h
Labels: enhancement

#77 firmware: axis: Fixed goto RA direction
  esp32_wireless_control/firmware/axis.cpp
Labels: bug

#75 add debug configuration and minor improvements
  esp32_wireless_control/firmware/commands.cpp
  esp32_wireless_control/firmware/common_strings.h
  esp32_wireless_control/firmware/firmware.ino
  esp32_wireless_control/firmware/platformio.ini
Labels: enhancement

#76 load star database items dynamically
  esp32_wireless_control/firmware/catalogues/bsc5/bsc5ra.cpp
  esp32_wireless_control/firmware/catalogues/bsc5/bsc5ra.h
  esp32_wireless_control/firmware/catalogues/ngc/ngc2000.cpp
  esp32_wireless_control/firmware/catalogues/ngc/ngc2000.h
  esp32_wireless_control/firmware/catalogues/star_database.cpp
  esp32_wireless_control/firmware/catalogues/star_database.h
  esp32_wireless_control/firmware/catalogues/star_database_interface.h
  esp32_wireless_control/firmware/interface/index.html
  esp32_wireless_control/firmware/languages/chineseLanguage.h
  esp32_wireless_control/firmware/languages/englishLanguage.h
  esp32_wireless_control/firmware/languages/germanLanguage.h
  esp32_wireless_control/firmware/languages/nextLanguage.h
  esp32_wireless_control/firmware/website/web_languages.cpp
  esp32_wireless_control/firmware/website/web_languages.h
Labels: bug, enhancement
